export const LOAD_RECIPIENTS = 'LOAD_RECIPIENTS',
			 LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS',
			 CHOSEN_CONVERSATION_MESSAGES = 'CHOSEN_CONVERSATION_MESSAGES',
			 CHOSEN_CONVERSATION = 'CHOSEN_CONVERSATION',
			 LOAD_CONVERSATIONS_SOCKET = 'LOAD_CONVERSATIONS_SOCKET',
			 UPDATE_CONVERSATION_MESSAGES = 'UPDATE_CONVERSATION_MESSAGES';