export const LOAD_RECIPIENTS = 'LOAD_RECIPIENTS',
			 LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS',
			 CHOSEN_CONVERSATION_MESSAGES = 'CHOSEN_CONVERSATION_MESSAGES',
			 CHOSEN_CONVERSATION = 'CHOSEN_CONVERSATION',
			 LOAD_CONVERSATIONS_SOCKET = 'LOAD_CONVERSATIONS_SOCKET',
			 UPDATE_CONVERSATION_MESSAGES = 'UPDATE_CONVERSATION_MESSAGES',
			 NEW_CONVERSATION = 'NEW_CONVERSATION',
			 UPDATE_RECIPIENT = 'UPDATE_RECIPIENT',
			 CHOSEN_CONVERSATION_AND_MESSAGES = 'CHOSEN_CONVERSATION_AND_MESSAGES',
			 CONVERSATION_BY_RECIPIENT = 'CONVERSATION_BY_RECIPIENT',
			 CHOSEN_RECIPIENT='CHOSEN_RECIPIENT',
			 CONVERSATION_MESSAGES  = 'CONVERSATION_MESSAGES',
			 RECIEVE_NEW_MESSAGE = 'RECIEVE_NEW_MESSAGE',
<<<<<<< HEAD
			 LOAD_SEARCH_USER = 'SEARCH_USER',
			 CLEAR_SEARCH = 'CLEAR_SEARCH';
=======
			 LOAD_SEARCH_USER = 'SEARCH_USER';
>>>>>>> c0611266efa6f5ae698e6a32cd06147f10acd9e8
