export const LOAD_RECIPIENTS = 'LOAD_RECIPIENTS',
			 LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS',
			 CHOSEN_CONVERSATION_MESSAGES = 'CHOSEN_CONVERSATION_MESSAGES',
			 CHOSEN_CONVERSATION = 'CHOSEN_CONVERSATION';